// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0gVO7-eU41MnUMLbhULIN7IJLP1uCyM0',
    appId: '1:527244845282:web:715cdc9145139bd5157ebb',
    messagingSenderId: '527244845282',
    projectId: 'es117-project',
    authDomain: 'es117-project.firebaseapp.com',
    storageBucket: 'es117-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8nhJU5prMaaBxNJtQeHJh-hMcGubYxc',
    appId: '1:527244845282:android:ade139305ebb1dc9157ebb',
    messagingSenderId: '527244845282',
    projectId: 'es117-project',
    storageBucket: 'es117-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd8A_OK6HjiumMuHDr4luUs6FGuBb5aiU',
    appId: '1:527244845282:ios:a3bb8fdb80805db6157ebb',
    messagingSenderId: '527244845282',
    projectId: 'es117-project',
    storageBucket: 'es117-project.appspot.com',
    iosClientId: '527244845282-vl4vii4qavdjimo8e7c6poc5lcpt02p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd8A_OK6HjiumMuHDr4luUs6FGuBb5aiU',
    appId: '1:527244845282:ios:a3bb8fdb80805db6157ebb',
    messagingSenderId: '527244845282',
    projectId: 'es117-project',
    storageBucket: 'es117-project.appspot.com',
    iosClientId: '527244845282-vl4vii4qavdjimo8e7c6poc5lcpt02p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.groupProject',
  );
}
